source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.0.2"
gem "rails", "~> 7.0.3"
gem "pg", "~> 1.1"
gem "puma", "~> 5.0"
gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]
gem "bootsnap", require: false
gem 'figaro', '~> 1.1'
gem 'uuid', '~> 2.3'
gem 'bcrypt', '~> 3.1'
gem 'jwt', '~> 1.5'
gem 'redis', '~> 4.6'
gem 'rack-cors'
gem 'prawn', '~> 2.1'
gem 'ruby-kafka'

group :development, :test do
  gem 'rspec-rails'
  gem 'factory_bot_rails'
  gem "debug", platforms: %i[ mri mingw x64_mingw ]
end
